### ISSUE TITLE
Programmatically build the metadata

### ISSUE THREAD

**Issue by csarven** [csarven/doingbusiness-linked-data#1]
Check whether it is possible (i.e., reliably) to build the metadata (e.g., DSDs, concepts, codes, properties) programmatically, instead of hand coding. Do it in several steps if necessary e.g.:
1. Tooling extracts as many terms as it can
2. Manually enhance the definitions

**Comment by reni99** [comment]
> Check whether it is possible (i.e., reliably) to build the metadata
> (e.g., DSDs, concepts, codes, properties) programmatically, instead of hand
> coding

Okey, I'll try that

2014-12-09 10:15 GMT+01:00 Sarven Capadisli notifications@github.com:

**Comment by reni99** [comment]
I wrote a script to generate the DSD file. Should I push it into the same directory (scripts/) where the actual scripts for the ETL will be?

**Comment by csarven** [comment]
Yes.

**Comment by reni99** [comment]
Has been pushed to
https://github.com/csarven/doingbusiness-linked-data/tree/dev/scripts

2014-12-15 16:19 GMT+01:00 Sarven Capadisli notifications@github.com:

**Comment by csarven** [comment]
re: https://github.com/csarven/doingbusiness-linked-data/commit/27c94e0a093c0c569f28f58813b762deb2af7228

Oh my goodness!

What I meant was that the script actually extracts the terms _for you_, so that you don't have to manually list them in the code. Typically, you would tell the script (whatever tool you are using to e.g., extract, map) to look for a particular location in the file, and then generate rest of the stuff.

What you have is a semi-automatic approach, which is an improvement from manually writing each part, but this is still a lot of work and repetition which you should try to avoid.

**Comment by csarven** [comment]
The point of aiming for automatic generation is so that you don't have to create two completely separate processes for building the metadata (e.g., DSD), and data (e.g., datasets). It is possible that what you have in https://github.com/csarven/doingbusiness-linked-data/commit/27c94e0a093c0c569f28f58813b762deb2af7228 is the best scenario but I would seriously encourage you to look into this again.

For instance, if you use tarql to build the dataset observations, why wouldn't it be possible to build its DSD and rest of the metadata? What is missing or insufficient? Try to address that because it will make your life much easier in the end.

**Comment by reni99** [comment]
Has been changed.
